---
# color is ยง
# next line "Exemple\nSalut"
Found: "contul a fost gasit"
Create: "si-a facut un cont"
Content: "ai primit x bani bla bla"
Bani: 25000
Folosit: "Ai folosit comanda asta pe acest cont!"

...